[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.12"
webp = {git = "https://github.com/jaredforth/webp.git"}
image = "0.24.5"
fast_image_resize = "2.6.0"