// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.12.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Frame {
  final Uint8List data;
  final int width;
  final int height;
  final int timestamp;

  const Frame({
    required this.data,
    required this.width,
    required this.height,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      data.hashCode ^ width.hashCode ^ height.hashCode ^ timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Frame &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          width == other.width &&
          height == other.height &&
          timestamp == other.timestamp;
}
