name: seventv_for_whatsapp
description: Use 7TV emotes as WhatsApp stickers
publish_to: none
version: 1.0.0+100000000
environment:
  sdk: ">=3.0.0"
dependencies:
  flutter:
    sdk: flutter
  universal_io: ^2.0.4
  shimmer: ^3.0.0
  whatsapp_stickers_handler:
    path: ./plugins/whatsapp_stickers_handler
  path_provider: ^2.0.11
  emoji_picker_flutter: ^1.5.1
  image: ^4.0.13
  shared_preferences: ^2.0.15
  ffi: ^2.0.1
  flutter_rust_bridge: ^1.59.0
  freezed_annotation: ^2.2.0
  ulid: ^2.0.0
  flutter_local_notifications: ^16.2.0
  json_annotation: ^4.8.0
  get_it: ^7.2.0
  url_launcher: ^6.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  ffigen: ^9.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  gitmoji:
    git:
      url: https://github.com/gthvmt/gitmoji-dart.git
flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/icon.png
  min_sdk_android: 21
  adaptive_icon_background: null
  adaptive_icon_foreground: assets/icons/icon.png
  web:
    generate: true
    image_path: assets/icons/icon.png
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: assets/icons/icon.png
    icon_size: 48
  macos:
    generate: true
    image_path: assets/icons/icon.png
