name: Build
on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    container:
      image: >-
        ghcr.io/${{ github.repository_owner }}/7tv4wa-dev:${{
        (github.event_name == 'pull_request' &&
        (github.event.pull_request.base.ref == 'development' ||
        github.event.pull_request.base.ref == 'master')) &&
        github.event.pull_request.base.ref ||
        'latest' }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}
      env:
        GITHUB_TOKEN: ${{secrets.TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{secrets.TOKEN}}
      - name: Build apk
        run: chmod +x .github/workflows/*.sh && .github/workflows/build.sh